version: '3.9'

x-open-responses: &open_responses
  image: masaicai/open-responses:0.0.3-alpha

services:
  # Flavor 1: Default service (runs when no profile is specified)
  open-responses:
    <<: *open_responses
    ports:
      - "8080:8080"
    environment:
      - TOOLS_MCP_ENABLED=false
    profiles:
      - default
  # Services used only in the MCP flavor.
  mcp-github:
    image: mcp/github
    command: ["echo", "Pulled mcp/github image"]
    restart: "no"
    profiles:
      - mcp

  mcp-brave-search:
    image: mcp/brave-search
    command: ["echo", "Pulled mcp/brave-search image"]
    restart: "no"
    profiles:
      - mcp

  # Flavor 2: MCP service that includes extra configuration and depends on the above.
  open-responses-mcp:
    <<: *open_responses
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
    depends_on:
      - mcp-github
      - mcp-brave-search
    profiles:
      - mcp

  # Flavor 2: replicated for Windows with named pipe
  open-responses-mcp-windows:
    image: masaicai/open-responses:0.0.3-alpha
    ports:
      - "8080:8080"
    volumes:
      # Use the Docker named pipe on Windows
      - "//./pipe/docker_engine://./pipe/docker_engine"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
    depends_on:
      - mcp-github
      - mcp-brave-search
    profiles:
      - mcp


  # Flavor 3: MCP service that includes extra configuration and custom path for mcp config json.
  open-responses-custom-mcp:
    <<: *open_responses
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ${MCP_CONFIG_FILE_PATH:-/app/default_mcp_config.json}:/app/mcp_server_config.json:ro
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - MCP_SERVER_CONFIG_FILE_PATH=/app/mcp_server_config.json
    depends_on:
      - mcp-github
      - mcp-brave-search
    profiles:
      - mcp

  #Flavour 3: replicated for Windows with named pipe
  open-responses-custom-mcp-windows:
    image: masaicai/open-responses:0.0.3-alpha
    ports:
      - "8080:8080"
    volumes:
      # Use the Docker named pipe on Windows
      - "//./pipe/docker_engine://./pipe/docker_engine"
      # Mount the MCP config file: if MCP_CONFIG_FILE_PATH is not defined, use the default path in the container
      - ${MCP_CONFIG_FILE_PATH:-/app/default_mcp_config.json}:/app/mcp_server_config.json:ro
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - MCP_SERVER_CONFIG_FILE_PATH=/app/mcp_server_config.json
    depends_on:
      - mcp-github
      - mcp-brave-search
    profiles:
      - mcp


  # Flavor 4: Run with openai-agent SDK settings.
  open-responses-with-openai:
    <<: *open_responses
    ports:
      - "8080:8080"
    environment:
      - TOOLS_MCP_ENABLED=false
      - MODEL_BASE_URL=${MODEL_BASE_URL}
    profiles:
      - openai

  # MongoDB service for persistent storage
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=openresponses
    profiles:
      - mongodb
    restart: unless-stopped

  # Flavor 5: Open Responses with MongoDB storage integration
  open-responses-with-mongodb:
    <<: *open_responses
    ports:
      - "8080:8080"
    environment:
      - TOOLS_MCP_ENABLED=false
      - OPEN_RESPONSES_MONGODB_DATABASE=openresponses
      - OPEN_RESPONSES_MONGODB_URI=mongodb://mongodb:27017
      - OPEN_RESPONSES_RESPONSE_STORE_TYPE=mongodb
    depends_on:
      - mongodb
    profiles:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data:
