receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  # Keep ONLY traces whose spans match any of these attributes
  tail_sampling/langfuse:
    decision_wait: 5s
    num_traces: 100000
    expected_new_traces_per_sec: 1000
    policies:
      - name: keep-url-path
        type: string_attribute
        string_attribute:
          key: uri
          values: ["/v1/responses"]
  batch:
    timeout: 5s
    send_batch_size: 512

exporters:
  # --- Langfuse (OTLP over HTTP/Protobuf) ---
  otlphttp/langfuse:
    # FULL traces URL (with /v1/traces) required by Langfuse
    traces_endpoint: https://cloud.langfuse.com:443/api/public/otel/v1/traces
    headers:
      Authorization: ${LANGFUSE_OTLP_AUTH}
    compression: gzip
    tls:
      insecure: false
    timeout: 10s

  # --- SigNoz (OTLP over HTTP/Protobuf) ---
  otlphttp/signoz:
    # Base URL; exporter appends /v1/{signal}
    endpoint: https://ingest.eu.signoz.cloud:443
    headers:
      signoz-ingestion-key: ${SIGNOZ_INGESTION_KEY}
    compression: gzip
    tls:
      insecure: false
    timeout: 10s

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]

  pipelines:
    # Langfuse gets ONLY traces that match the sampling policies above
    traces/langfuse:
      receivers: [otlp]
      processors: [tail_sampling/langfuse, batch]
      exporters: [otlphttp/langfuse]

    # SigNoz gets everything (no filtering)
    traces/signoz:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/signoz]

    metrics/signoz:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/signoz]

    logs/signoz:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/signoz]
