# Stage 1: Build your app image based on amazoncorretto
FROM bellsoft/liberica-openjre-alpine-musl:21

# Accept version as build argument
ARG BUILD_VERSION=0.8.1

RUN addgroup -S app && adduser -S app -G app
USER app

WORKDIR /app

# Copy the built JAR and configuration file into the image
COPY agc-platform-server/build/libs/agc-platform-server-${BUILD_VERSION}.jar /app/agc-platform-server-${BUILD_VERSION}.jar

# Copy the agc-client-runtime/java-sdk directory
COPY agc-client-runtime/java-sdk /app/agc-client-runtime/java-sdk

EXPOSE 6644
# Start the Java application directly
ENTRYPOINT java -jar /app/agc-platform-server-${BUILD_VERSION}.jar
