# Stage 1: Build your app image based on amazoncorretto
FROM bellsoft/liberica-openjre-alpine-musl:21

RUN addgroup -S app && adduser -S app -G app
USER app

WORKDIR /app

# Copy the built JAR and configuration file into the image
COPY agc-platform-server/build/libs/agc-platform-server-0.8.0-dev.jar /app/agc-platform-server-0.8.0-dev.jar

# Copy the agc-client-runtime/java-sdk directory
COPY agc-client-runtime/java-sdk /app/agc-client-runtime/java-sdk

EXPOSE 6644
# Start the Java application directly
ENTRYPOINT ["java", "-jar", "/app/agc-platform-server-0.8.0-dev.jar"]
