receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "*"

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1
    send_timestamps: true

extensions:
  health_check:
  pprof:
  zpages:


service:
  telemetry:
    logs:
      level: "debug"
    metrics:
      level: "detailed"
      address: "0.0.0.0:8888"
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, otlp, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
